name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull davidocta154/backend-magang:latest
    - name: Delete Old docker container
      run: sudo docker rm -f backend-magang-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p :8080 --name backend-magang-container davidocta154/backend-magang
